### ISSUE TITLE
Tango3 is not verifying job requests

### ISSUE THREAD

**Issue by droh** [autolab/Tango#10]
If the user specifies a non-existing VM image, Tango should return immediately with a validation error. It doesn't. Instead, Tango runs waitVM three times in an unsuccessful attempt to start a non-existing VM image. 

Tango should be doing extensive validation of job requests, which it apparently isn't.

**Comment by mihirpandya** [comment]
The check for an existing VM image was removed in the open sourced version of Tango3, since it is CMU specific, and was accidentally merged into prod. The check has been added again in prod (and tested) but not in the open sourced version.

**Comment by droh** [comment]
This kind of validation definitely needs to be in the open source version.
Otherwise people get very strange behavior when forget to update the VM
name. You can make it non-CMU specific by adding a config variable that
lists the pathname where images can be found.

-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh

**Comment by mihirpandya** [comment]
First, we check if Tashi is being used as the VMMS. If so, make sure that a directory is defined for the VM images, as `Config.TASHI_IMAGE_PATH`. 

Here's the piece of code that does that.

https://github.com/autolab/Tango/blob/master/tangod.py#L237
