### ISSUE TITLE
Autodriver has a hardcoded path /bin/find

### ISSUE THREAD

**Issue by droh** [autolab/Tango#101]
autodriver.c has a hard coded path to /bin/find, which causes it to break on ubuntu systems, which have find in /usr/bin/find.

**Comment by ymzong** [comment]
One solution I'm thinking of is to use `/usr/bin/env find` instead of `find`'s absolute path.

**Comment by nayak16** [comment]
Merged 5b67e37bf6862949b978c4fecfc1edd4f6698807
