### ISSUE TITLE
Restarting jobManager doesn't refresh the machines list

### ISSUE THREAD

**Issue by yrkumar** [autolab/Tango#108]
the total VM list is refreshed, but the free VM lists stay the same for some reason. this causes jobs to stall in the waiting phase instead of progressing to be assigned to new VMs.

**Comment by yrkumar** [comment]
will test this with the docker deployment and report back soon

**Comment by nayak16** [comment]
Related to #78

**Comment by nayak16** [comment]
@yrkumar Can this be prioritized over the Docker improvements?

**Comment by yrkumar** [comment]
@nayak16 sure

**Comment by yrkumar** [comment]
actually I tested this with the docker deployment (i.e. the environment with supervisor + nginx) and it seems like things are working fine... not sure why I thought that this was broken when I created the issue.  @nayak16 want to do a quick run-through of this as well and then we can close this issue?

**Comment by yrkumar** [comment]
on further investigation, this issue is actually the exact same as #78, closing it as duplicate.
