### ISSUE TITLE
Write documentation for VMMS API

### ISSUE THREAD

**Issue by yrkumar** [autolab/Tango#117]
VMMS API remains undocumented and it would be useful for people looking to add a different implementation of it.

**Comment by yrkumar** [comment]
@nayak16 v1 of this documentation is up at https://github.com/autolab/Tango/wiki/Tango-VMMS-API. Check it out and let me know if you want to make any changes. Otherwise, this issue will be closed.

**Comment by nayak16** [comment]
This looks pretty good. Only thing I would suggest is mentioning/linking to this API Doc on the Tango README so users are aware this exists. Also, to make it easier for people to be aware that they can write their own VMMS that conforms to the API.
