### ISSUE TITLE
Unable to import from vmms/

### ISSUE THREAD

**Issue by zyx-billy** [autolab/Tango#119]
As discussed today, after performing the setup instructions in the wiki, starting up the server with
`$ python restful-tango/server.py <port>`
causes an import error. 
tango.py will fail to import modules from the vmms directory.

One way to fix this is by simply adding an empty __init__.py inside the vmms directory.

**Comment by nayak16** [comment]
@zyx-billy Did you run this in the virtualenv using `source bin/activate` first?

**Comment by zyx-billy** [comment]
Yes I activated virtualenv first. There was the (Tango) label beside the command prompt. 

I basically followed the instructions in the wiki step by step, and ran into this issue in the start up guide.
