### ISSUE TITLE
Improve suggested deployment of Tango

### ISSUE THREAD

**Issue by yrkumar** [autolab/Tango#121]
This issue consists of many parts:
- [x] Add nginx and docker to the list of programs managed by supervisor
- [x] Make supervisor start these programs automatically when docker container is run
- [x] Expose ports on docker container so that Tango service is accessible from the outside 
- [ ] Use host's docker installation instead of docker-in-docker

**Comment by fanpu** [comment]
Resolved with docker-compose installation
