### ISSUE TITLE
Fix volumes path parsing in localDocker vmms

### ISSUE THREAD

**Issue by yrkumar** [autolab/Tango#122]
The whole `DOCKER_VOLUME_PATH` key and its parsing in `getVolumePath()` in `vmms/localDocker.py` is a bit wonky. Needs to be better explained in docs or just rewritten to be more clear.

**Comment by 20wildmanj** [comment]
This issue doesn't seem to be valid anymore as the `getVolumePath()` function was cleaned up in 2020
