### ISSUE TITLE
clients/tango-rest.py fails with `http://localhost` but works with `localhost`

### ISSUE THREAD

**Issue by 5nizza** [autolab/Tango#127]
Hey, 
I followed the instructions on testing tango and
`python clients/tango-rest.py -P <port> -k <key> -l <courselab> --open`
would cause an error if `-s` is left to default `http://localhost`.
But worked well is used with `-s localhost`
(without `http://` prefix)

### Expected Behavior
work

### Actual Behavior
fails with `Tango is not reachable on ..`.

### Steps to Reproduce the Behavior
Just run the default `python clients/tango-rest.py -P <port> -k <key> -l <courselab> --open`.

### Info

- `uname -a `:
Linux hell 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- default setup (localDocker)

- `/etc/hosts` has two lines : `127.0.0.1	localhost` and `127.0.1.1	hell`

### Minor Note

please change `./clients/tango-rest.py` last Exception handling to more informative:

      except Exception as e:
      print 'Tango not reachable on %s:%d!\n' % (args.server, args.port)
      print e
      sys.exit(0)

**Comment by ymzong** [comment]
Think this should be fixed by #126. @nayak16?

**Comment by nayak16** [comment]
Merged db7ad92
