### ISSUE TITLE
Installation Script

### ISSUE THREAD

**Issue by devanshk** [autolab/Tango#132]
We should have an installation script for Tango on Ubuntu.

**Comment by remzr7** [comment]
Isn't that one click?

**Comment by devanshk** [comment]
One click masks a lot of the functionality in Docker, which makes it better for production but less transparent for development. This one should function like the Autolab Ubuntu install script, setting up the files and directories like they would manually be setup.

**Comment by remzr7** [comment]
One click could be extended to have a dev mode?

**Comment by devanshk** [comment]
One-click is heavily dockerized so we'd need a whole different set of commands anyway. A separate script would be more lightweight.

**Comment by victorhuangwq** [comment]
Will be moving towards using Docker for easy deployments.

**Comment by fanpu** [comment]
Fixed with the docker install, see https://docs.autolabproject.com/docker-compose/
