### ISSUE TITLE
Dockerfile is broken

### ISSUE THREAD

**Issue by bjelline** [autolab/Tango#134]
### Expected Behavior

when I follow the [deployment installation instructions](https://autolab.github.io/docs/tango-deploy/) and run 
`docker build --tag="tango_deployment" .`
 I expect the docker image  "tango_deployment" to be built.

### Actual Behavior

the build fails with 

> W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/vivid/edge/binary-amd64/Packages  HttpError404
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c curl -sSL https://get.docker.com/ | sh' returned a non-zero code: 100

### Steps to Reproduce the Behavior

follow the [deployment installation instructions](https://autolab.github.io/docs/tango-deploy/) until you reach 

`run "docker build --tag="tango_deployment" .`

### What the problem might be

using ubuntu 15, "vivid" as the os for the container. In line 47 of the dockerfile 
docker is installed with `RUN curl -sSL https://get.docker.com/ | sh`
inside the container. This fails because Docker is not available for ubuntu 15 vivid.

**Comment by copperx** [comment]
Any fixes?

**Comment by fanpu** [comment]
Will be fixed by https://github.com/autolab/Tango/pull/186
