### ISSUE TITLE
213 labs are not autograding (high priority)

### ISSUE THREAD

**Issue by droh** [autolab/Tango#14]
With the exception of proxylab, 213 uses legacy .rb files that overload functions like autogradeInputFiles and parseAutoresult. None of the labs are autograding. Tango returns a status code of -3 to the front-end with no other feedback. 

Kosbie uses similar legacy .rb files, so he's going to be running into this issue as well.

**Comment by mihirpandya** [comment]
https://github.com/autolab/Autolab/pull/98 fixes it
