### ISSUE TITLE
Autograding. Error message: 795: unexpected token at '---'

### ISSUE THREAD

**Issue by ronzalo** [autolab/Tango#153]
### Context
AutoGrading a quiz with a ruby script and localDocker

### Expected Behavior
Autodriver ouput writed correctly

### Actual Behavior
Ruby `puts` output isn' writted

### Possible solution 
In https://github.com/autolab/Tango/blob/master/vmms/localDocker.py#L141, use `autolab > output/feedback 2>&1` instead `autolab &> output/feedback`

**Comment by s-wallace** [comment]
I can reproduce this problem as well; the localDocker call seems to work fine with an autograding image built on ubuntu 14.04, but not on 18.04 here are a few more details:

 - sh is invoked by localDocker which is dash 0.5.7 on ubuntu 14.04 and dash 0.5.8 on ubuntu 18.04
 - `autolab &> output/feedback` isn't strictly supported in dash (see https://wiki.ubuntu.com/DashAsBinSh) 

to reproduce:

1. build a docker autograding image based on ubuntu 14.04 (the current Dockerfile in Tango/vmms will work)
2. build a second based on unbuntu 18.04
3. run the command issued by localDocker, mine looks like:

```
docker run --rm --name grader -v <pathwithsubmission>:/home/mount autograding_image sh -c \
'cp -r mount/* autolab/; su autolab -c "autodriver -u 100 -f 1048576 -t 10 -o 524288 \
autolab &> output/feedback"; cp output/feedback mount/feedback'
```

This command works fine for me on a 14.04 image, and produces no output on a 18.04 image

4.  run the proposed command:
```
docker run --rm --name grader -v <pathwithsubmission>:/home/mount autograding_image sh -c \
'cp -r mount/* autolab/; su autolab -c "autodriver -u 100 -f 1048576 -t 10 -o 524288 \
autolab > output/feedback 2>&1"; cp output/feedback mount/feedback'
```

This produces correct output for both images.

**Comment by fanpu** [comment]
I am running into an issue where if this fix is used, autodriver seems to interpret `2>&1` as a token to parse instead:

```autolab@aede15bcd16e:/home$ autodriver -u 100 -f 104857600 -t 180 -o 1024000 autolab 2>&1 output/feedback
autodriver: Too many arguments```

This results in autograding not being performed at all.

Looking to see if there is an alternative solution

**Comment by fanpu** [comment]
Confirming that this works

**Comment by fanpu** [comment]
Fix now in master
