### ISSUE TITLE
Figure out a better, more consistent tab spacing

### ISSUE THREAD

**Issue by mihirpandya** [autolab/Tango#17]
The tab spacings are well weird on greatwhite, github and my local machine. Let's make this more consistent, somehow.

**Comment by ymzong** [comment]
As @Z1MM32M4N suggested, I think we can just use 4-space indentation.

**Comment by mihirpandya** [comment]
That's what i thought we had, but sometimes the 4 spaces are actual spaces, sometimes it's a tab of width 4... Don't understand why...

**Comment by ymzong** [comment]
@mihirpandya I guess that's caused by editor configs?

**Comment by dlbucci** [comment]
I vote for 2 space tabs as far as ruby, html, js, css are concerned.  Stick with 4 spaces for python.

**Comment by yrkumar** [comment]
^ that sounds good, I'm going to go reindent all the python files to make sure they have 4 space indents then

**Comment by Z1MM32M4N** [comment]
:+1: for @dlbucci's suggested conventions

**Comment by icanberk** [comment]
@yrkumar It might actually be a good idea to run files through Pyflake (https://pypi.python.org/pypi/pyflakes)
