### ISSUE TITLE
No more output after changing autograding-image to ubuntu:18.04

### ISSUE THREAD

**Issue by etwasanderes2** [autolab/Tango#170]
### What I did:
Changed the ubuntu version in the Dockerfile for the autograding image to 18.04.
I also needed to install sudo, as it is required by `autodriver/Makefile`.
[Dockerfile.txt](https://github.com/autolab/Tango/files/4812872/Dockerfile.txt)

### Expected Behavior:
I should get the hello-world output.
[Makefile.txt](https://github.com/autolab/Tango/files/4812874/Makefile.txt)
[expected-output.txt](https://github.com/autolab/Tango/files/4812868/expected-output.txt) (actual output with ubuntu 16.04)

### Actual Behavior:
I don't get the output that should be caused by the Makefile.
[actual-output.txt](https://github.com/autolab/Tango/files/4812878/actual-output.txt)
Note that `Autodriver: Job exited with status 0` is missing.

### Logs and debug information.
Ubuntu 16.04 still works.
[stdout.txt](https://github.com/autolab/Tango/files/4812882/stdout.txt)
[log.txt](https://github.com/autolab/Tango/files/4812883/log.txt)

**Comment by victorhuangwq** [comment]
I think this issue is possibly similar to this issue found here, and there is a solution provided there. https://github.com/autolab/Tango/issues/153
Let me know if this is relevant / addresses your problem.
