### ISSUE TITLE
Issue with scp failing

### ISSUE THREAD

**Issue by icanberk** [autolab/Tango#23]
Initially mentioned here: https://github.com/autolab/Autolab/issues/169

**Comment by robsimmons** [comment]
Any progress on this issue? I just did a regrade all that had a couple of failures, I've still got a bunch of misgrades for pixels I haven't fixed, and our workflow requires us to do a pretty work-intensive regrade all a week from tomorrow.

**Comment by robsimmons** [comment]
I... feel like a jerk poking this issue, but the grading two assignments for 122 is kind of blocked on it.

**Comment by icanberk** [comment]
Hi @robsimmons, We're really sorry for the inconvenience. Our Tango devs were a little busy with personal stuff the past week. I'll make sure that we fix this by this Friday!
