### ISSUE TITLE
Distributed autograding in Docker containers

### ISSUE THREAD

**Issue by droh** [autolab/Tango#52]
Write a "distributed-docker" module that allows autograding on a set of distributed machines, one job at a time on each machine, in a Docker container.

**Comment by icanberk** [comment]
Why does it need to be one job at a time on each machine?

**Comment by jez** [comment]
I think that we discussed that this would be the "simpler" option. There's no reason why we wouldn't want to eventually make use of all cores.

**Comment by droh** [comment]
We could make use of all cores by simply "prealloc'ing" one docker instance
for each core.

On Saturday, March 28, 2015, Jake Zimmerman <notifications@github.com>
wrote:

> I think that we discussed that this would be the "simpler" option. There's
> no reason why we wouldn't want to eventually make use of all cores.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autolab/Tango/issues/52#issuecomment-87299868>.
>


-- 
Sent from my iPhone.

**Comment by jez** [comment]
I don't think there's an analog to prealloc in Docker. If you have a job
with Docker, you just run it; there's no need to prealloc.

**Comment by droh** [comment]
The Tango scheduler, which is independent of any particular vmms, is designed
around the idea of matching a job with a free instance. So to get the same
behavior as our current Tashi system, we would simply prealloc 40 (5
backend servers x 8 cores per sever) and then round robin schedule.

On Saturday, March 28, 2015, Jake Zimmerman <notifications@github.com>
wrote:

> I don't think there's an analog to prealloc in Docker. If you have a job
> with Docker, you just run it; there's no need to prealloc.
>
> On Sat, Mar 28, 2015 at 11:50 PM droh <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > We could make use of all cores by simply "prealloc'ing" one docker
> instance
> > for each core.
> >
> > On Saturday, March 28, 2015, Jake Zimmerman <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > I think that we discussed that this would be the "simpler" option.
> > There's
> > > no reason why we wouldn't want to eventually make use of all cores.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/autolab/Tango/issues/52#issuecomment-87299868>.
> > >
> >
> >
> > --
> > Sent from my iPhone.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/autolab/Tango/issues/52#issuecomment-87349161>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autolab/Tango/issues/52#issuecomment-87349284>.
>


-- 
Sent from my iPhone.

**Comment by mihirpandya** [comment]
The PR for this: https://github.com/autolab/Tango/pull/69
