### ISSUE TITLE
Tango needs a JSON API client on Ruby

### ISSUE THREAD

**Issue by ymzong** [autolab/Tango#53]
I'm going to work on the Ruby API client and put the code into autolab front-end repository.

**Comment by dlbucci** [comment]
Why does it need this?

**Comment by ymzong** [comment]
Our front-end code has a lot of interaction between Autolab and Tango, and currently the code is not clean. Technically the work will be done in front-end repo, but it belongs to Tango.

**Comment by dlbucci** [comment]
I'd make this issue in the front-end repo.  I do like the idea of moving Tango code into a module or class, because that would make it easier to swap out autograding backends, if a user was so inclined.  We'd just have to write an adapter for a backend.

**Comment by ymzong** [comment]
That's right -- I'll also make an issue on front-end repo. I'd like to keep this issue here though, so people who want to play with Tango by itself can also use it.

**Comment by jez** [comment]
Probably the resulting project would be packed up as a separate repo and shipped as a Ruby Gem, so I don't know whether either repo is a good place to house this issue.

**Comment by icanberk** [comment]
I love the Ruby Gem idea. We can also make modules for other languages later if people want to use tango with Python etc.

Let's make a separate repo then?

**Comment by ymzong** [comment]
@icanberk I'm thinking about creating a `module TangoClient` under `lib/` for now, and maybe our summer intern can factor it out into a separate repo / gem?

**Comment by yrkumar** [comment]
Closing this issue - this is addressed by https://github.com/autolab/Autolab/pull/425
