### ISSUE TITLE
`elapsed_secs` field in `info` endpoint is wrong

### ISSUE THREAD

**Issue by ymzong** [autolab/Tango#70]
When I hit `/info` endpoint in the API, the `elapsed_secs` variable is shown as the current epoch time (e.g. `1429372581`) instead of the actual number of seconds elapsed.

May you forgot to save the time when Tango was started?

**Comment by ymzong** [comment]
See `config.template.py:L114`.

**Comment by nayak16** [comment]
Fix merged f736923
