### ISSUE TITLE
json output is hard to parse

### ISSUE THREAD

**Issue by cg2v** [autolab/Tango#81]
The JSON output of getInfo and getPool uses JSON Arrays of ["a=X", "b=Y"] instead of Objects {"a":X, "b": Y}. This makes them non trivial to parse, since the client has to dive into the string rather then letting a JSON library do all the work for it. 

Is there a reason for doing things this way?

**Comment by yrkumar** [comment]
Closed by f779953331647955b55d0174b07b2ceaded452b5
