### ISSUE TITLE
Recent change in MD5 hash function seems to break Autolab integration

### ISSUE THREAD

**Issue by GjjvdBurg** [autolab/Tango#90]
Hi there,

I came across an issue where if I deleted an assessment in Autolab and reuploaded it, Tango would grade the latest file submitted to the previously deleted assessment when a new file was submitted to the reuploaded assessment (even if the files differ). Since there was an update in commit 050e5fcd3a6e5af1644cf606c9a2eb9bb0fa5b42 which had to do with MD5 checking, I updated Tango to see if this solved my issue. Unfortunately, this lead me to this error in Autolab:

![screenshot from 2015-09-15 01-46-31](https://cloud.githubusercontent.com/assets/3286696/9864958/a8ce6852-5b4f-11e5-89a9-73eee1ec8c53.png)

After doing some digging in the source, it seems like the output from Tango's open() function in tangoREST.py is incompatible with what Autolab expects since the commit mentioned above. As you can see from the screenshot, the error finally occurs in `tango_upload` in Autolab's `autograde.rb`, but is due to the `existing_files` variable which is obtained from a `TangoClient.open(..)` call.

Thanks for looking into this.

**Comment by yrkumar** [comment]
Thanks for the detailed screenshots! 

@ymzong, has the Autolab codebase been updated to reflect the change to Tango's `open` implementation from 050e5fc?

**Comment by dlbucci** [comment]
@yrkumar Haven't noticed it yet.

**Comment by yrkumar** [comment]
@GjjvdBurg, this should be fixed now by 5092c7270dc5d1e0ac83374847c0989591de127e.

**Comment by GjjvdBurg** [comment]
Thanks @yrkumar!
